# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('do_type', models.SmallIntegerField(blank=True, choices=[(0, '出库'), (1, '入库'), (2, '调拨'), (3, '报废')], null=True, verbose_name='设备状态')),
                ('use_num', models.IntegerField(default=0, verbose_name='使用次数')),
                ('out_num', models.IntegerField(default=0, verbose_name='出库次数')),
                ('in_num', models.IntegerField(default=0, verbose_name='入库次数')),
                ('life', models.IntegerField(default=400, verbose_name='使用寿命')),
            ],
            options={
                'verbose_name': '保温箱设备',
                'verbose_name_plural': '保温箱设备',
            },
        ),
        migrations.CreateModel(
            name='DeviceAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(max_length=100, verbose_name='类型')),
                ('move_num', models.IntegerField(default=0, verbose_name='流转数量')),
                ('number', models.IntegerField(default=0, verbose_name='总数量')),
                ('destination', models.CharField(blank=True, max_length=20, null=True, verbose_name='目的仓库')),
            ],
            options={
                'verbose_name': '保温箱类型',
                'verbose_name_plural': '保温箱类型',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('message', models.CharField(max_length=100, verbose_name='操作信息')),
                ('time', models.CharField(max_length=20, verbose_name='记录时长')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '操作信息',
                'verbose_name_plural': '操作信息',
            },
        ),
    ]
