# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20180129_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='use_num',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='use_num',
            field=models.IntegerField(default=0, verbose_name='使用寿命'),
        ),
        migrations.AlterField(
            model_name='deviceattr',
            name='type',
            field=models.CharField(max_length=100, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=20, verbose_name='操作时间'),
        ),
    ]
