# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_device_is_destroy'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='do_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='操作类型'),
        ),
    ]
