# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_message_do_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='move_num',
            field=models.IntegerField(default=0, verbose_name='流转数量'),
        ),
        migrations.AlterField(
            model_name='message',
            name='do_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='操作动作'),
        ),
    ]
