# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20180130_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='move_num',
        ),
        migrations.RemoveField(
            model_name='message',
            name='use_num',
        ),
        migrations.AddField(
            model_name='device',
            name='use_num',
            field=models.IntegerField(default=0, verbose_name='使用寿命'),
        ),
        migrations.AddField(
            model_name='message',
            name='move_num',
            field=models.IntegerField(default=0, verbose_name='流转数量'),
        ),
        migrations.AlterField(
            model_name='device',
            name='life',
            field=models.IntegerField(default=400, verbose_name='寿命时长'),
        ),
    ]
