# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20180130_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
