# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 09:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20180129_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='number',
            new_name='now_num',
        ),
    ]
